image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo "exec zsh" >> ~/.bashrc && echo "ZSH_THEME_TERM_TITLE_IDLE=\"\${ZSH_THEME_TERM_TAB_TITLE_IDLE}\"" >> ~/.zshrc
    command: bash /workspace/evol-gitpod/scripts/start.sh && cd ~/.evol && exec zsh

checkoutLocation: evol-gitpod
workspaceLocation: evol-gitpod/evol-gitpod.theia-workspace

ports:
 - port: 3306 # mysql
   onOpen: ignore # never prompt, never expose
 - port: 5900
   onOpen: ignore # never prompt, never expose

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    addCheck: false
    addComment: false
